# Generated by Django 3.2.6 on 2021-11-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../static/img/logo.png', upload_to='uploads'),
        ),
    ]
