# Generated by Django 3.2.9 on 2021-11-12 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='../static/img/3.jpg', upload_to='uploads'),
        ),
    ]
